name: Receive Flight Data

on:
  repository_dispatch:
    types: [flight-update]

permissions:
  contents: write

jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Write state.json
        env:
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD" > state.json

      - name: Commit and push
        run: |
          git config --global user.email "droughtbot@github.com"
          git config --global user.name "DroughtBot"
          git add state.json
          git diff --staged --quiet && echo "No changes" || git commit -m "live: flight update"
          git push
